version: "1"

run:
  max-same-issues: 0

linters:
  enable:
    - errcheck        # Checks for errors that are not checked.
    - govet           # Reports suspicious constructs found by the Go vet tool.
    - ineffassign     # Detects ineffectual assignments.
    - staticcheck     # A suite of static analysis checks for Go.
    - unused          # Checks for unused constants, variables, functions and types.
    - gosec           # Inspects Go code for security problems.
    - gosimple        # Simplifies code.
    - typecheck       # Reports type checking errors.
    - dogsled         # Checks for assignments to variables in loops.
    - goprintffuncname # Checks for consistent use of Printf-like function names.
    - copyloopvar     # Checks for usage of the variable in the loop's scope.
    - stylecheck      # Enforces style guidelines (alternative to golint).  Note:  This is deprecated.  Consider revive.
    - unconvert       # Removes unnecessary type conversions.
    - gocritic        # Provides code suggestions.
    - revive          # Fast, configurable, extensible, and accurate linter for Go.
    - sloglint        # Checks for best practices with log/slog

linters-settings:
  gci:
    prefix: https://github.com/Br0ce/opera

formatters:
  enable:
    - gci         # Formats import groups.
    - gofmt       # Formats Go code.
    - goimports   # Adds/removes import statements.
    - golines     # Helps to automatically fix long lines in Go code.
