# This file is for local development only.

services:

  opera:
    image: "mcr.microsoft.com/devcontainers/go:1-1.24-bookworm"
    volumes:
      - ../..:/workspaces:cached
      # - ${HOME}${USERPROFILE}/.netrc:/root/.netrc:ro,cached
      # - ${HOME}${USERPROFILE}/.ssh:/root/.ssh:ro,cached
    command: sleep infinity

  weather:
        build:
            context: ./mock/weather
        restart: always
        container_name: weather
        environment:
            - ADDR=:8080
            - SLEEP_TIME=5s
            - RANDOM_FAIL=false
            - TRACING_ADDR=tracing:4318

  shark:
        build:
            context: ./mock/shark
        restart: always
        container_name: shark
        environment:
            - ADDR=:8080
            - SLEEP_TIME=5s
            - RANDOM_FAIL=false
            - TRACING_ADDR=tracing:4318
 
  tracing:
    image: jaegertracing/jaeger:2.5.0
    container_name: jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
